import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const date = new Date()
  const copywriteDate = date.getFullYear()
  return (
    <div className={styles.container}>
      <Head>
        <title>Park Circle Skate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pc-favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={`${styles.themeBlueColor} text-5xl text-center`}>
          Welcome to Park Circle Skate
        </h1>
        <div className="m-10">
          <Image
            src="/pc-skate-logo.png"
            alt="Park Circle Skate wheel Logo"
            width={200}
            height={200}
          />
        </div>
        <div className="w-full text-center text-2xl italic mb-20 p-12 bg-gradient-to-r from-indigo-50 via-indigo-100">
          <p>
            We are a group of people in the Park Circle area of North
            Charleston, SC who are advocating for a free to use, safe, and
            inclusive concrete skatepark for our community to enjoy.
          </p>
        </div>
        <div className="mb-28 text-center max-w-xl px-6 flex flex-col gap-8">
          <h2 className="text-3xl mb-2">The Problem</h2>
          <div className="text-left">
            <p className="text-xl">
              The City of North Charleston has provided Park Circle residents
              with a variety of recreational spaces with many being renovated to
              offer the best facilities to the deserving community. However, one
              important activity that is considered an athletic sport and an art
              form has been overlooked by city planning, and that is
              skateboarding.
            </p>
            <p className="italic text-sm mt-4">
              &quot;It is surprising to learn that many cities and towns in the
              United States don&apos;t have a single skatepark. It&apos;s easy
              to find a basketball hoop or a baseball diamond almost anywhere
              you go. Yet when it comes to skateboarding, skaters have little
              choice but to ride on the sidewalks, on the streets, school
              campuses, parking lots, and other places around town... or simply
              don&apos;t skate at all. They show an uncommon dedication to their
              sport. And what does this commitment to physical exercise and
              outdoor activity earn them? In many areas it gets them a big
              fine.&quot; (
              <a
                className="text-sky-600 hover:text-sky-700"
                href="https://publicskateparkguide.org/vision/the-skateboarding-problem/"
                target="_blank"
                rel="noreferrer"
              >
                https://publicskateparkguide.org/vision/the-skateboarding-problem/
              </a>
              )
            </p>
          </div>
        </div>
        <div className="w-full mt-4 bg-slate-50">
          <div className="text-center">
            <h2 className="text-3xl pt-8 mb-2">Why a Skatepark?</h2>
            <div className="p-8 text-left mx-10">
              <div className="flex justify-center gap-8">
                <div className="max-w-xl">
                  <ul className="list-disc text-slate-900">
                    <li className="mb-2">
                      There are 8.8 million skateboarders in the U.S. Up 34%
                      from 2019, and this does not account for the many other
                      skatepark users, like BMX riders, roller/quad skaters,
                      inline skaters, scooter riders, and more. (
                      <a
                        className="text-sky-600 hover:text-sky-700"
                        href="https://www.sfia.org/reports/962_Skateboarding-Participation-Report-2021"
                        target="_blank"
                        rel="noreferrer"
                      >
                        https://www.sfia.org/reports/962_Skateboarding-Participation-Report-2021
                      </a>
                      )
                    </li>
                    <li className="mb-2">
                      Most of the these skateboarders are 24 years old or
                      younger. (
                      <a
                        className="text-sky-600 hover:text-sky-700"
                        href="https://publicskateparkguide.org/vision/the-skateboarding-problem/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        https://publicskateparkguide.org/vision/the-skateboarding-problem/
                      </a>
                      )
                    </li>
                    <li className="mb-2">
                      Skateboarding is the third most commonly reported interest
                      for high school students (24% of girls, and 17% of boys).
                      (
                      <a
                        className="text-sky-600 hover:text-sky-700"
                        href="https://www.aspeninstitute.org/wp-content/uploads/2021/11/Aspen-National-Student-Survey-FINAL-Report.pdf"
                        target="_blank"
                        rel="noreferrer"
                      >
                        https://www.aspeninstitute.org/wp-content/uploads/2021/11/Aspen-National-Student-Survey-FINAL-Report.pdf
                      </a>
                      )
                    </li>
                    <li className="mb-2">
                      Skateparks are the fourth most used recreation space in
                      terms of total weekly use hours. They were found to be
                      more popular than sports fields, play areas, fitness
                      zones, and dog parks when comparing the total weekly use
                      hours. (
                      <a
                        className="text-sky-600 hover:text-sky-700"
                        href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5030121/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5030121/
                      </a>
                      )
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="mb-28 mt-20 text-center">
          <h2 className="text-3xl mb-6">Skateparks Build Communities</h2>
          <div className={styles.videoWrapper}>
            <iframe
              width="560"
              height="315"
              src="https://www.youtube.com/embed/RUo8XXptXkc"
              title="YouTube video player - The Skatepark Project, Building Communities"
              frameBorder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen
            ></iframe>
          </div>
        </div>
        <div className="p-12 bg-slate-100 text-center">
          <h2 className="text-3xl mb-6">Keep up with us on social media!</h2>
          <div className={styles.grid}>
            <a
              href="https://instagram.com/parkcircleskate"
              target="_blank"
              rel="noreferrer"
              className={styles.card}
            >
              <h2>@parkcircleskate</h2>
              <p>Follow us on Instagram!</p>
            </a>

            <a
              href="https://www.facebook.com/groups/882978432691586/"
              target="_blank"
              rel="noreferrer"
              className={styles.card}
            >
              <h2>Park Circle Skate</h2>
              <p>Join our Facebook group!</p>
            </a>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>© {copywriteDate}</footer>
    </div>
  )
}
