import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const date = new Date()
  const copywriteDate = date.getFullYear()
  return (
    <div className={styles.container}>
      <Head>
        <title>Park Circle Skate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pc-favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-4xl text-center">Welcome to Park Circle Skate</h1>
        <div className="m-10">
          <Image
            src="/pc-skate-logo.png"
            alt="Park Circle Skate wheel Logo"
            width={200}
            height={200}
          />
        </div>
        <p className="text-2xl mb-6">
          <code className={styles.code}>Site under construction...</code>
        </p>
        <p className="text-2xl mb-6">
          Meanwhile, you can check us out on social media!
        </p>
        <div className={styles.grid}>
          <a
            href="https://instagram.com/parkcircleskate"
            className={styles.card}
          >
            <h2>@parkcircleskate</h2>
            <p>Follow us on Instagram!</p>
          </a>

          <a
            href="https://www.facebook.com/groups/882978432691586/"
            className={styles.card}
          >
            <h2>Park Circle Skate</h2>
            <p>Join our Facebook group!</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>© {copywriteDate}</footer>
    </div>
  )
}
